console.log("como hacer panqueques");
console.log("ingredientes: harina 500g, 4 huevo, 1litro de leche");
console.log("batir los huevo con la leche");
console.log("agregar la harina a la mezcla");
console.log("encender la ornalla");
console.log("calentar la sarten");
console.log("agregar a la sarten una cucharada de manteca");
console.log("agregar la mezcla a la sarten");
console.log("esperar que se cocine de un lado ");
console.log("darlo vuelta");
console.log("retirar de la sarten");
console.log("repetir la secuencia hasta terminar la mezcla");
